// ---- ERROR CONSTANTS
export const SET_AUTH_ERR_MSG = "SET_AUTH_ERR_MSG";
export const CLEAR_AUTH_ERR_MSG = "CLEAR_AUTH_ERR_MSG";
export const SET_PROFILE_ERR_MSG = "SET_PROFILE_ERR_MSG";
export const SET_NEWSFEED_ERR_MSG = "SET_NEWSFEED_ERR_MSG";

// ---- SETTINGS CONSTANTS
export const SET_THEME = "SET_THEME";
