// ---- AUTH CONSTANTS
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const CHECK_SESSION = "CHECK_SESSION";
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// ---- ERROR CONSTANTS
export const SET_AUTH_ERR_MSG = "SET_AUTH_ERR_MSG";
export const CLEAR_AUTH_ERR_MSG = "CLEAR_AUTH_ERR_MSG";
export const SET_PROFILE_ERR_MSG = "SET_PROFILE_ERR_MSG";
export const SET_NEWSFEED_ERR_MSG = "SET_NEWSFEED_ERR_MSG";

// ---- SETTINGS CONSTANTS
export const SET_THEME = "SET_THEME";
